// examples/nuxt-example/app/app.vue
<script setup lang="ts">
import { Avatar } from "@avatune/vue";
import theme from "@avatune/pacovqzz-theme/vue";
</script>

<template>
  <div class="container">
    <NuxtRouteAnnouncer />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?12" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?34" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?56" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?78" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?90" />
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  align-items: center;
  gap: 3rem;
}
</style>

// examples/angular-ssr-example/src/app/app.ts
import { Component } from '@angular/core'
import { Avatar } from '@avatune/angular'
import theme from '@avatune/pacovqzz-theme/angular'

@Component({
  selector: 'app-root',
  imports: [Avatar],
  template: `
    <div style="display: flex; flex-wrap: wrap; align-items: center; gap: 3rem; padding: 2rem">
      @for (seed of seeds; track seed) {
        <avatune-avatar [theme]="theme" [inputSize]="64" [seed]="seed" />
      }
    </div>
  `,
  styles: [],
})
export class App {
  protected readonly theme = theme
  protected readonly seeds = ['angular-ssr-1', 'angular-ssr-2', 'angular-ssr-3', 'angular-ssr-4', 'angular-ssr-5']
}
