// examples/nuxt-example/app/app.vue
<script setup lang="ts">
import { Avatar } from "@avatune/vue";
import theme from "@avatune/pacovqzz-theme/vue";
</script>

<template>
  <div class="container">
    <NuxtRouteAnnouncer />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?12" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?34" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?56" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?78" />
    <Avatar :size="64" :theme="theme" seed="https://github.com/shadcn.png?90" />
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  align-items: center;
  gap: 3rem;
}
</style>

// examples/nextjs-example/src/app/page.tsx
import { Avatar as AvatuneAvatar } from "@avatune/react";
import theme from "@avatune/pacovqzz-theme/react";

export default function Home() {
  return (
    <div className="flex flex-row flex-wrap items-center gap-12">
      <AvatuneAvatar
        size={64}
        theme={theme}
        seed="https://github.com/shadcn.png?12"
      />
      <AvatuneAvatar
        size={64}
        theme={theme}
        seed="https://github.com/shadcn.png?34"
      />
      <AvatuneAvatar
        size={64}
        theme={theme}
        seed="https://github.com/shadcn.png?56"
      />
      <AvatuneAvatar
        size={64}
        theme={theme}
        seed="https://github.com/shadcn.png?78"
      />
      <AvatuneAvatar
        size={64}
        theme={theme}
        seed="https://github.com/shadcn.png?90"
      />
    </div>
  );
}
